<?php
/* LICENSE
 * 
 * BanSE - a site base (designed to be the SCEngine website)
 * Copyright (C) 2007-2012 Colomban Wendling <ban@herbesfolles.org>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

/* layout for all pages */

require_once ('include/defines.php');
require_once ('lib/UrlTable.php');
require_once ('lib/User.php');
require_once ('lib/Route.php');
require_once ('lib/Flash.php');
require_once ('lib/string.php');
require_once ('lib/Metadata.php'); /* gives MDI instance */


function print_head_adds (&$adds) {
	$added = array ();
	
	foreach ($adds as $add) {
		if (! in_array ($add, $added)) {
			echo $add;
			$added[] = $add;
		}
	}
	
	unset ($added, $add);
}


header('Content-Type: text/html; charset=UTF-8');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" >
	<head>
		<title><?php echo TITLE,' &mdash; ',Metadata::get_instance ()->get_name (); ?></title>
		
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<meta name="description" content="<?php echo DESCRIPTION; ?>" />
		
		<link rel="start" title="Accueil" href="<?php echo UrlTable::home (); ?>" />
		<link rel="icon" href="<?php echo BSE_BASE_PATH,'styles/',STYLE; ?>/icon.png" type="image/png" />
		<link rel="stylesheet" media="screen" type="text/css" title="default"
			href="<?php echo BSE_BASE_PATH,'styles/',STYLE; ?>/main.css" />
		
		<link rel="alternate" title="Actualités (Atom)"
			type="application/atom+xml" href="<?php echo BSE_BASE_PATH,NEWS_ATOM_FEED_FILE; ?>" />
		<link rel="alternate" title="Actualités (RSS)"
			type="application/rss+xml" href="<?php echo BSE_BASE_PATH,NEWS_RSS_FEED_FILE; ?>" />
		
		<script type="text/javascript" src="<?php echo BSE_BASE_PATH ?>include/js/actions.js"></script>
<?php
			if (isset ($HEAD_ADDS) && is_array ($HEAD_ADDS)) {
				print_head_adds ($HEAD_ADDS);
			}
?>
	</head>

	<body>
		<div id="header">
			<div id="banner">
				<h1><a href="<?php echo UrlTable::home (); ?>" accesskey="1"><?php echo Metadata::get_instance ()->get_name (); ?></a></h1>
			</div>

			<div id="menubar">
				<ul>
				<?php
					$menubar = array (
						'Home'          => 'index',
						'News'          => 'news',
						'Medias'        => 'medias',
						'Downloads'     => 'downloads',
						'Forums'        => 'forums/',
						'Documentation' => 'doc/',
						//'License'       => 'license',
						'About'         => 'about'
					);
					
					if (User::get_logged ()) {
						$menubar['Admin'] = 'admin.php';
					}
					
					foreach ($menubar as $title => $link) {
						$route = new Route ($link);
						$current = '';
						
						if ($controller == $route->controller) {
							$current = 'class="current"';
						}
						
						echo '<li ',$current,'><a href="',$route,'">',$title,'</a></li>';
					}
				?>
				</ul>
			</div>

			<!--div id="navbar">
				You are here: 
			</div-->
		</div>

		<div id="body">

<?php if (($messages = Flash::get_messages ())): ?>
		<div class="messages">
			<?php foreach ($messages as $message): ?>
				<p class="message <?php echo $message['type'] ?>">
					<?php echo $message['message'] ?>
				</p>
			<?php endforeach ?>
		</div>
<?php endif ?>

<?php
if (is_object ($template)) {
	$template->render ();
} else {
	echo $template;
}
?>

		</div> <!-- body -->

		<div id="footer">
			<div class="module">
				<h3>Support</h3>
				<ul>
						<li><a href="<?php echo BSE_BASE_PATH; ?>forums/">Forum</a></li>
						<li><a href="<?php echo BSE_BASE_PATH; ?>doc/">Documentation</a></li>
				</ul>
			</div>
			
			<!--div class="module">
				<h3>Contributing</h3>
				<ul>
					<li><a href="<?php echo BSE_BASE_PATH; ?>tracker">Bug tracker</a></li>
					<li><a href="<?php echo BSE_BASE_PATH; ?>docs/contributing">How to help?</a></li>
					<li><a href="<?php echo BSE_BASE_PATH; ?>about/donation">Make a donation</a></li>
				</ul>
			</div-->
			
			<div class="module">
				<h3>Miscellaneous</h3>
				<ul>
					<li><a href="<?php echo UrlTable::license (); ?>">License</a></li>
				</ul>
			</div>
			
			<div class="module">
				<h3>Administration</h3>
				<ul>
				<?php if (User::get_logged ()) { ?>
					<li><a href="<?php echo UrlTable::admin (); ?>">Administration</a></li>
					<li><a href="<?php echo UrlTable::admin ('actualités'); ?>">Manage news</a></li>
					<li><a href="<?php echo UrlTable::admin ('medias'); ?>">Manage medias</a></li>
					<li><a href="<?php echo UrlTable::admin ('administrateurs'); ?>">Manage users</a></li>
					<li><a href="<?php echo UrlTable::logout (); ?>">Log out</a></li>
				<?php } else { ?>
					<li><a href="<?php echo UrlTable::login (); ?>">Log in</a></li>
				<?php } ?>
				</ul>
			</div>
			
			<div class="clearer"></div>
			
			<!--p><a href="http://validator.w3.org/check?uri=referer">xHTML 1.0</a></p-->
			<p>
				<a href="<?php echo BSE_TAR_FILE; ?>">BanSE</a>,
				Copyright &copy; 2007-2012 Colomban Wendling &lt;<?php echo obfuscate_email ('ban@herbesfolles.org'); ?>&gt;
				This whole site is licensed under the GNU GPL v3 or later.
				See <a href="<?php echo LICENSE_URL; ?>" accesskey="8">license</a> for more details.
				&mdash;
				Kindly hosted by <a href="http://www.tuxfamily.org">TuxFamily</a>.
			</p>
			
			<?php
				if (User::get_logged ()) {
					echo '<table><caption>SQL queries:</caption>';
					foreach (MyDB::get_query_log () as $query) {
						echo '<tr><td>',$query,'</td></tr>';
					}
					echo '</table>';
				}
			?>
		</div>

	</body>
</html>
