<?php if (empty ($urls)): ?>
<p>No media to display</p>
<?php else: ?>
<div id="main-image-box">
	<a href="<?php echo UrlTable::medias () ?>">
		<img id="main-image" src="<?php echo $urls[0] ?>" alt="" />
	</a>
</div>
<script type="text/javascript">
	<!--
	slideshow (
		document.getElementById ('main-image'),
		document.getElementById ('main-image-box'),
		Array('<?php echo implode ('\',\'', $urls) ?>'),
		5000,
		1000
	);
	//-->
</script>
<?php endif ?>
