<?php include ('common-top.phtml') ?>

<?php if (! $media): ?>
	<h3>Invalid media</h3>
	<p>The media you are looking for does not exist.</p>
<?php else: ?>
	<h3 id="watch"><?php echo Html::escape ($media['desc']) ?></h3>
	<div class="showmediacontainer">
		<?php if ($is_admin): ?>
			<div class="admin">
				[<a href="<?php echo UrlTable::admin_medias ('edit', $media['id']) ?>">Edit</a>]
				[<a href="<?php echo UrlTable::admin_medias ('rm', $media['id']) ?>">Delete</a>]
			</div>
		<?php endif ?>
		
		<div class="media">
			<?php if ($media['type'] == MediaType::SCREENSHOT): ?>
				<a href="<?php echo $media['uri'] ?>"
				   title="<?php echo $media['desc'] ?>">
					<img src="<?php echo $media['uri'] ?>"
					     alt="<?php echo $media['desc'] ?>"
					     style="max-width:100%;" />
				</a>
			<?php elseif ($media['type'] == MediaType::MOVIE): ?>
				<object type="<?php echo $media['mime_type'] ?>"
				        data="<?php echo $media['uri'] ?>"
				        width="100%" height="400">
					<param name="src" value="<?php echo $media['uri'] ?>"></param>
					<a href="<?php echo $media['uri'] ?>">
						<img src="<?php echo $media['tb_uri'] ?>"
						     alt="<?php echo $media['desc'] ?>" />
					</a>
				</object>
			<?php else: /* Unknown type, display thumbnail only */ ?>
				<a href="<?php echo $media['uri'] ?>"
				   title="<?php echo $media['desc'] ?>">
					<img src="<?php echo $media['tb_uri'] ?>"
					     alt="<?php echo $media['desc'] ?>"
					     style="max-width:100%;" />
				</a>
			<?php endif ?>
		</div>
		
		<div class="links">
			[<a href="<?php echo $media['uri'] ?>">Direct link</a>]
		</div>
		
		<div class="links tags">
			Tags:
			<ul>
				<?php if (empty ($media['tags'])): ?>
					<li><a href="<?php echo UrlTable::medias_tags (array ($media['type'])) ?>">Not tagged</a></li>
				<?php else: ?>
					<?php foreach ($media['tags'] as $tag): ?>
						<li><a href="<?php echo UrlTable::medias_tags (array ($media['type']), array ($tag)) ?>"><?php echo $tag ?></a></li>
					<?php endforeach ?>
				<?php endif ?>
			</ul>
		</div>
		
		<?php if ($media['comment']): ?>
			<div class="comment">
				<p>
					<?php echo $media['comment'] ?>
				</p>
			</div>
		<?php endif ?>
		
		<?php if ($is_admin): ?>
			<?php media_print_code_snippets ($media) /* FIXME */ ?>
		<?php endif ?>
	</div>
<?php endif ?>

<p class="links">
	<?php if ($noreturn): ?>
		<?php echo Html::button ('Back', UrlTable::medias ()) ?>
	<?php else: ?>
		<?php echo Html::backbutton ('Back', UrlTable::medias ()) ?>
	<?php endif ?>
</p>

<?php include ('common-bottom.phtml') ?>
