<div id="presentation">
	<h2>About the SCEngine</h2>
	<p>
     The engine was created by Antony Martin in september 2006.
     From a self-teaching project, the engine has been rewritten to
     become a usable library with a pretty decent set of features.
	</p>
</div>

<div id="content">
	<h3>Authors</h3>
	<?php foreach ($roles as $role => $people): ?>
		<?php if (! empty ($people)): ?>
			<h4><?php echo $role ?></h4>
			<ul>
				<?php foreach ($people as $person): ?>
					<li><?php echo $person ?></li>
				<?php endforeach ?>
			</ul>
		<?php endif ?>
	<?php endforeach ?>
        <h3 id="contact">Contact</h3>
	  <ul>
            <li>Mailing list:
                <?php echo obfuscate_email ('scengine@lists.tuxfamily.org'); ?>.</li>
            <li>IRC channel: <a href="irc://irc.freenode.org/scengine">
                 irc://irc.freenode.org/scengine</a>.</li>
            <li>Administrator e-mail:
                <?php echo obfuscate_email ('antony.martin@scengine.org'); ?>.</li>
	  </ul>
</div>
