<?php
	/* support not to have a news */
	$_action	= isset ($news['id']) ? 'edit' : 'new';
	$_id			= isset ($news['id']) ? $news['id'] : '';
	$_title		= isset ($news['title']) ? $news['title'] : '';
	$_source	= isset ($news['source']) ? $news['source'] : '';
	$_publish	= isset ($news['published']) ? $news['published'] : true;
?>
<div class="formedit" id="fn<?php echo $_id ?>" <?php if ($hidden_forms): ?>style="display:none;"<?php endif ?>>
	<form method="post" action="<?php echo BSE_BASE_PATH ?>post.php?sec=news&amp;act=<?php echo $_action ?>&amp;id=<?php echo $_id ?>">
		<div>
			<label><span class="u">T</span>itle:<br />
				<input type="text" name="title" accesskey="t" value="<?php echo Html::escape ($_title) ?>" />
			</label>
			<br />
			<label for="tn<?php echo $_id ?>"><span class="u">C</span>ontent:</label>
			<div class="bcode-editor">
				<div class="form_toolbar">
				<?php
					echo Html::button_js ('+', "entry_more('tn$_id')", 'Enlarge the form');
					echo Html::button_js ('-', "entry_lesser('tn$_id')", 'Shrink the form');
					echo Html::button_js ('http://', "textarea_insert('tn$_id', '[[', ']]')", 'Insert Link (Alt+L)', 'l');
					echo Html::button_js ('img', "textarea_insert('tn$_id', '{{', '|Alternative text}}')", 'Insert Image (Alt+H)', 'h');
					echo Html::button_js ('<span class="b">B</span>', "textarea_insert_around('tn$_id', '**')", 'Bold (Alt+B)', 'b');
					echo Html::button_js ('<span class="i">I</span>', "textarea_insert_around('tn$_id', '//')", 'Italic (Alt+I)', 'i');
					echo Html::button_js ('<span class="u">U</span>', "textarea_insert_around('tn$_id', '__')", 'Underline (Alt+U)', 'u');
					echo Html::button_js ('<span class="s">S</span>', "textarea_insert_around('tn$_id', '--')", 'Strikethrough (Alt+S)', 's');
				?>
				</div>
				<textarea name="content" cols="24" rows="16" accesskey="C" id="tn<?php echo $_id ?>"><?php echo $_source ?></textarea>
			</div>
			<div class="options">
				<ul>
					<li><label title="Whether the news should be visible to all"><input type="checkbox" name="publish" <?php if ($_publish): ?>checked="checked"<?php endif ?> />Publish</label></li>
					<?php if ($_action == 'edit'): ?>
					<li><label title="Whether not to update modification date and author"><input type="checkbox" name="noupdate" checked="checked" />Hide edition</label></li>
					<?php endif ?>
				</ul>
			</div>
			<input type="submit" value="Post" accesskey="P" title="Post (Alt+P)" />
			<!--input type="reset" value="Reset" accesskey="X" title="Reset Form (Alt+X)" /-->
		</div>
	</form>
</div>
